version: '3.7'

services:
  mongo:
    image: mongo:4.4.3-bionic
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: go-recipes
    volumes:
      - ./create-user.js:/docker-entrypoint-initdb.d/create-user.js
      - ./seed-data.js:/docker-entrypoint-initdb.d/seed-data.js
