version: '3.7'

## --- Network ---
networks:
  go-network:
    driver: bridge

# --- Services ---
services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    hostname: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "./data/:/pulsar/data"
    networks:
      - go-network
  pulsar-manager:
    image: apachepulsar/pulsar-manager
    container_name: pulsar-manager
    hostname: pulsar-manager
    depends_on:
      - pulsar
    links:
      - pulsar
    ports:
      - "9527:9527"
      - "7750:7750"
    environment:
      - "SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties"
    networks:
      - go-network
