// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pkg

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitializeServer() (*HTTPServer, error) {
	settings := NewSettings()
	db, err := OpenConnection(settings)
	if err != nil {
		return nil, err
	}
	dataStore, err := NewDataStore(db)
	if err != nil {
		return nil, err
	}
	httpServer := NewHTTPServer(settings, dataStore)
	return httpServer, nil
}
